import { LayoutContainer } from '~/components/LayoutContainer';
import { Seo } from '~/components/Seo';

export interface SocialLink {
  label: string;
  url: string;
  icon: {
    path: string;
    colorClassname: string;
  };
}

export interface IndexPageProps {
  links: SocialLink[];
}

const IndexPage = ({ links }: IndexPageProps) => (
  <LayoutContainer>
    <Seo title="Welcome" />
    <div>
      <div className="m-0 px-5 text-center tracking-tighter xxl:px-16">
        <div className="m-0 text-center py-1-vru xxl:py-1-vru-xxl">
          <h1 className="m-0 font-code tracking-tighter text-h2 xxl:text-h2-xxl">
            Robert Harbul
          </h1>
          <p className="text-h6 xxl:text-h6-xxl">Software Engineer</p>
        </div>
      </div>
      <div className="flex-auto px-5 xxl:px-16">
        <section className="flex flex-row items-center justify-center py-1-vru xxl:py-1-vru-xxl">
          {links.map((item) => (
            <a
              key={item.url}
              className={`${item.icon.colorClassname} px-2 xxl:px-4`}
              href={item.url}
              aria-label={item.label}
              target="_blank"
              rel="noopener noreferrer me"
            >
              {/* Generated by IcoMoon.io */}
              <svg
                className="h-8 w-8 fill-current xxl:h-10 xxl:w-10"
                version="1.1"
                xmlns="http://www.w3.org/2000/svg"
                width="512"
                height="512"
                viewBox="0 0 512 512"
                aria-hidden="true"
              >
                <title>{item.label}</title>
                <path d={item.icon.path} />
              </svg>
            </a>
          ))}
        </section>
      </div>
      <div className="tracking-tight">
        <div className="px-5 text-center py-1-vru xxl:px-16 xxl:py-1-vru-xxl">
          ©{new Date().getFullYear()}, Built by{' '}
          <span className="font-semibold">@probwebdev</span> with{' '}
          <a
            href="https://nextjs.org/"
            aria-label="Next.js by Vercel - The React Framework"
            target="_blank"
            rel="noopener noreferrer"
          >
            NextJS
          </a>
        </div>
      </div>
    </div>
  </LayoutContainer>
);

// eslint-disable-next-line @typescript-eslint/require-await
export async function getStaticProps(): Promise<{ props: IndexPageProps }> {
  return {
    props: {
      links: [
        {
          label: 'Github Profile',
          url: 'https://github.com/probwebdev',
          icon: {
            path: 'm256 6.321c-141.37 0-256 114.61-256 256 0 113.11 73.352 209.07 175.07 242.92 12.793 2.369 17.496-5.555 17.496-12.316 0-6.102-0.24-26.271-0.348-47.662-71.224 15.488-86.252-30.205-86.252-30.205-11.641-29.588-28.424-37.458-28.424-37.458-23.226-15.889 1.755-15.562 1.755-15.562 25.7 1.805 39.238 26.383 39.238 26.383 22.836 39.135 59.888 27.82 74.502 21.279 2.294-16.543 8.926-27.84 16.253-34.232-56.865-6.471-116.64-28.425-116.64-126.52 0-27.949 10.002-50.787 26.38-68.714-2.658-6.45-11.427-32.486 2.476-67.75 0 0 21.503-6.876 70.42 26.245 20.418-5.674 42.318-8.518 64.077-8.617 21.751 0.099 43.668 2.943 64.128 8.617 48.867-33.122 70.328-26.245 70.328-26.245 13.936 35.264 5.175 61.3 2.518 67.75 16.41 17.928 26.347 40.766 26.347 68.714 0 98.327-59.889 119.98-116.9 126.31 9.182 7.945 17.362 23.523 17.362 47.406 0 34.254-0.298 61.822-0.298 70.254 0 6.814 4.611 14.797 17.586 12.283 101.66-33.888 174.92-129.81 174.92-242.88 0-141.39-114.62-256-256-256z',
            colorClassname: 'text-social-github',
          },
        },
        {
          label: 'LinkedIn Profile',
          url: 'https://www.linkedin.com/in/robert-harbul-66a77348/',
          icon: {
            path: 'm128 112c0 26.51-21.49 48-48 48s-48-21.49-48-48 21.49-48 48-48 48 21.49 48 48zm-96 80h96v288h-96zm160 0h88.553v45.391h1.266c12.32-22.097 42.479-45.391 87.421-45.391 93.473 0 110.76 58.188 110.76 133.87v154.13h-92.305v-136.64c0-32.592-0.667-74.513-48.014-74.513-48.074 0-55.41 35.493-55.41 72.146v139.01h-92.271z',
            colorClassname: 'text-social-linkedin',
          },
        },
      ],
    },
  };
}

export default IndexPage;
