packages:
  - apps/*
  - packages/*
  - tooling/*
catalog:
  react: ~19.1.0
  react-dom: ~19.1.0
  typescript: ~5.8.3
  next: ~15.3.3
  '@next/bundle-analyzer': ~15.3.3
  '@next/eslint-plugin-next': ~15.3.3
  eslint-config-next: ~15.3.3
onlyBuiltDependencies:
  - esbuild
  - unrs-resolver
