packages:
  - 'apps/*'
  - 'packages/*'
  - 'tooling/*'

catalog:
  react: ~18.3.1
  react-dom: ~18.3.1
  typescript: ~5.6.3
  next: ~15.1.6
  "@next/bundle-analyzer": ~15.1.6
  "@next/eslint-plugin-next": ~15.1.6
  eslint-config-next: ~15.1.6
