global:
  checkNewVersion: true
  sendAnonymousUsage: true

entryPoints:
  web:
    address: ":80"

providers:
  docker:
    watch: true
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    swarmMode: false

log:
  level: INFO

accessLog:
  filePath: "/var/log/traefik/access.log"

api:
  dashboard: true
  insecure: false
  debug: false
